/*
** ###################################################################
**     THIS MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals.
**            By default it is empty. Select "Generate Code"
**            to produce initialization code.
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

#ifndef __mcuinit_H
#define __mcuinit_H 1

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */

extern void MCU_init(void);
/*
** ===================================================================
**     Method      :  MCU_init
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/


/* END mcuinit */

#endif

/*
** ###################################################################
**
**     This file was created by Processor Expert
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
